services:
  sing-box:
    image: ${SING_BOX_IMAGE:-ghcr.io/xiaofujie369/xboard-singbox-anyreality-v1:1.1.0}
    container_name: sing-box
    restart: always
    network_mode: host
    volumes:
      - ./config:/etc/sing-box
      - ./logs:/var/log/sing-box
    command: ["-D", "/var/lib/sing-box", "-C", "/etc/sing-box", "run"]
